name: flutter_nice
description: DingStock Module

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: base/
  home:
    path: home/
  circle:
    path: circle/
  mine:
    path: mine/
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/tabbar_home_dark.png
    - assets/images/tabbar_home_light.png
    - assets/images/tabbar_monitoring_dark.png
    - assets/images/tabbar_monitoring_light.png
    - assets/images/tabbar_compare_light.png
    - assets/images/tabbar_compare_dark.png
    - assets/images/tabbar_circle_light.png
    - assets/images/tabbar_circle_dark.png
    - assets/images/tabbar_me_light.png
    - assets/images/tabbar_me_dark.png
    - assets/images/mine_about_us.png
    - assets/images/mine_feedback.png
    - assets/images/mine_focus_areas.png
    - assets/images/mine_integral_balance.png
    - assets/images/mine_integral_mall.png
    - assets/images/mine_issue.png
    - assets/images/mine_mall_bg.png
    - assets/images/mine_mall_vip.png
    - assets/images/mine_man.png
    - assets/images/mine_online_service.png
    - assets/images/mine_price.png
    - assets/images/mine_woman.png

    - assets/mine_item.json

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf


  module:
    androidX: true
    androidPackage: cn.cheney.flutter_nice
    iosBundleIdentifier: cn.cheney.flutterNice
