name: flutter_nice
description: A new Flutter module.

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: base/
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section, 
  # like this:
  assets:
    - images/tabbar_home_dark.png
    - images/tabbar_home_light.png
    - images/tabbar_monitoring_dark.png
    - images/tabbar_monitoring_light.png
    - images/tabbar_compare_light.png
    - images/tabbar_compare_dark.png
    - images/tabbar_circle_light.png
    - images/tabbar_circle_dark.png
    - images/tabbar_me_light.png
    - images/tabbar_me_dark.png

  module:
    androidX: true
    androidPackage: cn.cheney.flutter_nice
    iosBundleIdentifier: cn.cheney.flutterNice
