name: flutter_nice
description: DingStock Module

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: base/
  home:
    path: home/
  circle:
    path: circle/
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/tabbar_home_dark.png
    - images/tabbar_home_light.png
    - images/tabbar_monitoring_dark.png
    - images/tabbar_monitoring_light.png
    - images/tabbar_compare_light.png
    - images/tabbar_compare_dark.png
    - images/tabbar_circle_light.png
    - images/tabbar_circle_dark.png
    - images/tabbar_me_light.png
    - images/tabbar_me_dark.png

  module:
    androidX: true
    androidPackage: cn.cheney.flutter_nice
    iosBundleIdentifier: cn.cheney.flutterNice
