name: mine
description: A  mine package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../base/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

